"""Conversion to and from hashes. This module contains functions to convert
to and from 28-bit hashes into a human-readable (sort of) format. The naming
scheme is very simple: adverb-verb-animal where each section maps to a
bit range.
"""
ADVERBS = [
    'aback', 'abaft', 'abandoned', 'abashed', 'aberrant', 'abhorrent',
    'abiding', 'abject', 'ablaze', 'able', 'abnormal', 'aboard', 'aboriginal',
    'abortive', 'abounding', 'abrasive', 'abrupt', 'absent', 'absorbed',
    'absorbing', 'abstracted', 'absurd', 'abundant', 'abusive', 'acceptable',
    'accessible', 'accidental', 'accurate', 'acidic', 'acoustic', 'acrid',
    'actually', 'adamant', 'adaptable', 'addicted', 'adhesive', 'adjoining',
    'adorable', 'adventurous', 'afraid', 'aggressive', 'agreeable',
    'alcoholic', 'alert', 'alike', 'alleged', 'alluring', 'aloof', 'amazing',
    'ambiguous', 'ambitious', 'amuck', 'amused', 'amusing', 'ancient',
    'angry', 'animated', 'annoyed', 'annoying', 'anxious', 'apathetic',
    'aquatic', 'aromatic', 'arrogant', 'ashamed', 'aspiring', 'assorted',
    'astonishing', 'attractive', 'auspicious', 'automatic', 'available',
    'average', 'awake', 'awesome', 'axiomatic', 'barbarous', 'bashful',
    'bawdy', 'beautiful', 'befitting', 'belligerent', 'beneficial', 'bent',
    'berserk', 'bewildered', 'big', 'billowy', 'bitesized', 'bitter',
    'bizarre', 'bloody', 'blushing', 'boiling', 'boorish', 'bored', 'boring',
    'bouncy', 'boundless', 'brainy', 'brash', 'brave', 'brawny', 'breakable',
    'breezy', 'brief', 'bright', 'broad', 'broken', 'bumpy', 'burly',
    'bustling', 'busy', 'cagey', 'calculating', 'callous', 'calm', 'capable',
    'capricious', 'careful', 'careless', 'caring', 'cautious', 'certain',
    'changeable', 'charming', 'cheap', 'cheerful', 'chemical', 'childlike',
    'chilly', 'chivalrous', 'chubby', 'chunky', 'clammy', 'classy', 'clean',
    'clear', 'clever', 'cloistered', 'cloudy', 'clumsy', 'cluttered',
    'coherent', 'cold', 'colorful', 'colossal', 'combative', 'comfortable',
    'common', 'complete', 'complex', 'concerned', 'condemned', 'confused',
    'conscious', 'cooing', 'cool', 'cooperative', 'coordinated', 'courageous',
    'cowardly', 'crabby', 'craven', 'crazy', 'creepy', 'crooked', 'crowded',
    'cruel', 'cuddly', 'cultured', 'cumbersome', 'curious', 'curly', 'curved',
    'curvy', 'cute', 'cynical', 'daffy', 'daily', 'damaged', 'damp',
    'dangerous', 'dapper', 'dark', 'dashing', 'dazzling', 'dead', 'deadpan',
    'deafening', 'dear', 'debonair', 'decisive', 'decorous', 'deep',
    'defeated', 'defective', 'defiant', 'delicate', 'delicious', 'delightful',
    'delirious', 'demonic', 'dependent', 'depressed', 'deranged',
    'descriptive', 'deserted', 'detailed', 'determined', 'devilish', 'didactic',
    'different', 'difficult', 'diligent', 'direful', 'dirty', 'disagreeable',
    'disastrous', 'discreet', 'disgusted', 'disgusting', 'disillusioned',
    'dispensable', 'distinct', 'disturbed', 'divergent', 'dizzy', 'doubtful',
    'drab', 'draconian', 'dramatic', 'dreary', 'drunk', 'dry', 'dull', 'dusty',
    'dynamic', 'dysfunctional', 'eager', 'early', 'earsplitting', 'earthy',
    'eatable', 'economic', 'educated', 'efficacious', 'efficient', 'elastic',
    'elated', 'elderly', 'electric', 'elegant', 'embarrassed', 'eminent',
    'empty', 'enchanted', 'enchanting', 'encouraging', 'endurable', 'energetic',
    'enormous', 'entertaining', 'enthusiastic', 'envious', 'equable', 'erect',
    'erratic', 'ethereal', 'evanescent', 'evasive', 'excellent', 'excited',
    'exciting', 'exclusive', 'exotic', 'expensive', 'exuberant', 'exultant',
    'fabulous', 'faded', 'faint', 'fair', 'faithful', 'fallacious', 'familiar',
    'famous', 'fanatical', 'fancy', 'fantastic', 'fascinated', 'fast', 'fat',
    'faulty', 'fearful', 'fearless', 'feeble', 'feigned', 'female', 'fertile',
    'festive', 'fierce', 'filthy', 'fine', 'finicky', 'first', 'fixed',
    'flagrant', 'flaky', 'flashy', 'flat', 'flawless', 'flimsy', 'flippant',
    'flowery', 'fluffy', 'fluttering', 'foamy', 'foolish', 'foregoing',
    'forgetful', 'fortunate', 'fragile', 'frail', 'frantic', 'free',
    'freezing', 'frequent', 'fresh', 'fretful', 'friendly', 'frightened',
    'frightening', 'full', 'fumbling', 'functional', 'funny', 'furry',
    'furtive', 'future', 'futuristic', 'fuzzy', 'gabby', 'gainful', 'gamy',
    'gaping', 'garrulous', 'gaudy', 'general', 'gentle', 'giant', 'giddy',
    'gifted', 'gigantic', 'glamorous', 'gleaming', 'glib', 'glistening',
    'glorious', 'glossy', 'godly', 'good', 'goofy', 'gorgeous', 'graceful',
    'grandiose', 'grateful', 'gratis', 'greasy', 'great', 'greedy',
    'grieving', 'groovy', 'grotesque', 'grouchy', 'grubby', 'gruesome',
    'grumpy', 'guarded', 'guiltless', 'gullible', 'gusty', 'guttural',
    'habitual', 'half', 'hallowed', 'halting', 'handsome', 'handsomely',
    'handy', 'hanging', 'hapless', 'happy', 'hard', 'harmonious', 'harsh',
    'hateful', 'heady', 'healthy', 'heartbreaking', 'heavenly', 'heavy',
    'hellish', 'helpful', 'helpless', 'hesitant', 'hideous', 'high',
    'highfalutin', 'highpitched', 'hilarious', 'hissing', 'historical',
    'holistic', 'hollow', 'homeless', 'homely', 'honorable', 'horrible',
    'hospitable', 'hot', 'huge', 'hulking', 'humdrum', 'humorous', 'hungry',
    'hurried', 'hurt', 'hushed', 'husky', 'hypnotic', 'hysterical', 'icky',
    'icy', 'idiotic', 'ignorant', 'illegal', 'illustrious', 'imaginary',
    'immense', 'imminent', 'impartial', 'imperfect', 'impolite', 'important',
    'impossible', 'incandescent', 'incompetent', 'inconclusive', 'incredible',
    'industrious', 'inept', 'inexpensive', 'infamous', 'innate', 'innocent',
    'inquisitive', 'insidious', 'instinctive', 'intelligent', 'interesting',
    'internal', 'invincible', 'irate', 'irritating', 'itchy', 'jaded',
    'jagged', 'jazzy', 'jealous', 'jittery', 'jobless', 'jolly', 'joyous',
    'judicious', 'juicy', 'jumbled', 'jumpy', 'juvenile', 'kaput', 'keen',
    'kind', 'kindhearted', 'kindly', 'knotty', 'knowing', 'knowledgeable',
    'labored', 'lackadaisical', 'lacking', 'lame', 'lamentable', 'languid',
    'large', 'laughable', 'lavish', 'lazy', 'lean', 'legal', 'lethal', 'level',
    'lewd', 'likeable', 'limping', 'literate', 'little', 'lively', 'living',
    'lonely', 'longing', 'loose', 'lopsided', 'loud', 'lovely', 'loving',
    'lowly', 'lucky', 'ludicrous', 'lumpy', 'lush', 'luxuriant', 'lyrical',
    'macabre', 'macho', 'maddening', 'madly', 'magical', 'magnificent',
    'majestic', 'makeshift', 'malicious', 'mammoth', 'maniacal', 'marked',
    'married', 'marvelous', 'massive', 'material', 'materialistic', 'mature',
    'mean', 'measly', 'meaty', 'medical', 'meek', 'mellow', 'melodic',
    'melted', 'merciful', 'messy', 'mighty', 'military', 'milky', 'mindless',
    'miniature', 'minor', 'miscreant', 'misty', 'mixed', 'moaning', 'modern',
    'moldy', 'momentous', 'motionless', 'mountainous', 'muddled', 'mundane',
    'murky', 'mushy', 'mute', 'mysterious', 'naive', 'nappy', 'narrow',
    'nasty', 'natural', 'naughty', 'nauseating', 'neat', 'nebulous',
    'necessary', 'needless', 'needy', 'neighborly', 'nervous', 'new', 'nice',
    'nifty', 'nimble', 'nippy', 'noiseless', 'noisy', 'nonchalant',
    'nondescript', 'nonstop', 'normal', 'nostalgic', 'nosy', 'noxious',
    'numberless', 'numerous', 'nutritious', 'nutty', 'oafish', 'obedient',
    'obeisant', 'obese', 'obnoxious', 'obscene', 'obsequious', 'observant',
    'obsolete', 'obtainable', 'oceanic', 'odd', 'offbeat', 'old',
    'oldfashioned', 'omniscient', 'onerous', 'opposite', 'optimal', 'ordinary',
    'organic', 'ossified', 'outgoing', 'outrageous', 'outstanding',
    'overconfident', 'overjoyed', 'overrated', 'overt', 'overwrought',
    'painful', 'painstaking', 'pale', 'paltry', 'panicky', 'panoramic',
    'parched', 'parsimonious', 'past', 'pastoral', 'pathetic', 'peaceful',
    'penitent', 'perfect', 'periodic', 'permissible', 'perpetual', 'petite',
    'phobic', 'physical', 'picayune', 'piquant', 'placid', 'plain', 'plastic',
    'plausible', 'pleasant', 'plucky', 'pointless', 'poised', 'polite',
    'political', 'possessive', 'possible', 'powerful', 'precious', 'premium',
    'present', 'pretty', 'previous', 'pricey', 'prickly', 'private',
    'probable', 'productive', 'profuse', 'protective', 'proud', 'psychedelic',
    'psychotic', 'public', 'puffy', 'pumped', 'puny', 'purring', 'pushy',
    'puzzled', 'puzzling', 'quaint', 'quarrelsome', 'questionable', 'quick',
    'quickest', 'quiet', 'quirky', 'quixotic', 'quizzical', 'rabid', 'ragged',
    'rainy', 'rambunctious', 'rampant', 'rapid', 'rare', 'raspy', 'ratty',
    'ready', 'real', 'rebel', 'receptive', 'recondite', 'redundant',
    'reflective', 'regular', 'relieved', 'remarkable', 'reminiscent',
    'repulsive', 'resolute', 'resonant', 'responsible', 'rhetorical', 'rich',
    'right', 'righteous', 'rightful', 'rigid', 'ripe', 'ritzy', 'roasted',
    'robust', 'romantic', 'roomy', 'rotten', 'rough', 'round', 'royal',
    'ruddy', 'rude', 'rural', 'rustic', 'ruthless', 'safe', 'salty', 'sassy',
    'satisfying', 'savory', 'scandalous', 'scarce', 'scared', 'scary',
    'scattered', 'scientific', 'scintillating', 'scrawny', 'screeching',
    'secondhand', 'secretive', 'sedate', 'seemly', 'selective', 'selfish',
    'separate', 'serious', 'shaggy', 'shaky', 'shallow', 'sharp', 'shiny',
    'shivering', 'shocking', 'short', 'shrill', 'silent', 'silky', 'silly',
    'simple', 'simplistic', 'sincere', 'skillful', 'skinny', 'sleepy', 'slimy',
    'slippery', 'sloppy', 'slow', 'small', 'smart', 'smelly', 'smiling',
    'smoggy', 'smooth', 'sneaky', 'snobbish', 'snotty', 'soft', 'soggy',
    'solid', 'somber', 'sophisticated', 'sordid', 'sore', 'sour', 'sparkling',
    'sparse', 'special', 'spectacular', 'spicy', 'spiffy', 'spiky',
    'spiritual', 'spiteful', 'splendid', 'spooky', 'spotless', 'spotted',
    'spotty', 'spurious', 'squalid', 'square', 'squealing', 'squeamish',
    'stale', 'standing', 'statuesque', 'steadfast', 'steady', 'steep',
    'stereotyped', 'sticky', 'stiff', 'stimulating', 'stingy', 'stormy',
    'straight', 'strange', 'striped', 'strong', 'stupendous', 'stupid',
    'sturdy', 'subdued', 'subsequent', 'substantial', 'successful', 'succinct',
    'sudden', 'sulky', 'super', 'superb', 'superficial', 'supreme', 'swanky',
    'sweet', 'sweltering', 'swift', 'symptomatic', 'taboo', 'tacit', 'tacky',
    'talented', 'tall', 'tame', 'tan', 'tangible', 'tangy', 'tart', 'tasteful',
    'tasteless', 'tasty', 'tawdry', 'tearful', 'tedious', 'telling',
    'temporary', 'tender', 'tense', 'tenuous', 'terrible', 'terrific',
    'tested', 'testy', 'thankful', 'therapeutic', 'thick', 'thin', 'thinkable',
    'thirsty', 'thoughtful', 'thoughtless', 'threatening', 'thundering',
    'tidy', 'tight', 'tightfisted', 'tiny', 'tired', 'tiresome', 'toothsome',
    'torpid', 'tough', 'towering', 'tranquil', 'trashy', 'tremendous',
    'tricky', 'trite', 'troubled', 'truculent', 'true', 'truthful', 'typical',
    'ubiquitous', 'ugliest', 'ugly', 'ultra', 'unable', 'unaccountable',
    'unadvised', 'unarmed', 'unbecoming', 'unbiased', 'uncovered',
    'understood', 'undesirable', 'unequal', 'unequaled', 'uneven', 'unhealthy',
    'uninterested', 'unique', 'unkempt', 'unknown', 'unnatural', 'unruly',
    'unsightly', 'unsuitable', 'untidy', 'unused', 'unusual', 'unwieldy',
    'unwritten', 'upbeat', 'uppity', 'upset', 'uptight', 'used', 'useful',
    'useless', 'utopian', 'utter', 'uttermost', 'vacuous', 'vagabond', 'vague',
    'valuable', 'various', 'vast', 'vengeful', 'venomous', 'verdant', 'versed',
    'victorious', 'vigorous', 'violent', 'violet', 'vivacious', 'voiceless',
    'volatile', 'voracious', 'vulgar', 'wacky', 'waggish', 'waiting',
    'wakeful', 'wandering', 'wanting', 'warlike', 'warm', 'wary', 'wasteful',
    'watery', 'weak', 'wealthy', 'weary', 'wet', 'whimsical', 'whispering',
    'whole', 'wholesale', 'wicked', 'wide', 'wideeyed', 'wiggly', 'wild',
    'willing', 'windy', 'wiry', 'wise', 'wistful', 'witty', 'woebegone',
    'wonderful', 'wooden', 'woozy', 'workable', 'worried', 'wrathful',
    'wretched', 'wrong', 'wry', 'xenophobic', 'yielding', 'young', 'youthful',
    'yummy', 'zany', 'zealous', 'zesty', 'zippy', 'zonked']

VERBS = [
    'abiding', 'accelerating', 'accepting', 'accomplishing', 'achieving',
    'acquiring', 'acting', 'activating', 'adapting', 'adding', 'addressing',
    'administering', 'admiring', 'admitting', 'adopting', 'advising',
    'affording', 'agreeing', 'alerting', 'alighting', 'allowing', 'altering',
    'amusing', 'analyzing', 'announcing', 'annoying', 'answering',
    'anticipating', 'apologizing', 'appearing', 'applauding', 'applying',
    'appointing', 'appraising', 'appreciating', 'approving', 'arbitrating',
    'arguing', 'arising', 'arranging', 'arresting', 'arriving', 'ascertaining',
    'asking', 'assembling', 'assessing', 'assisting', 'assuring', 'attaching',
    'attacking', 'attaining', 'attempting', 'attending', 'attracting',
    'auditing', 'avoiding', 'awaking', 'backing', 'baking', 'balancing',
    'banging', 'banning', 'baring', 'bathing', 'batting', 'battling',
    'beaming', 'bearing', 'beating', 'becoming', 'begging', 'beginning',
    'behaving', 'beholding', 'being', 'belonging', 'bending', 'besetting',
    'betting', 'bidding', 'binding', 'biting', 'bleaching', 'bleeding',
    'blessing', 'blinding', 'blinking', 'blotting', 'blowing', 'blushing',
    'boasting', 'boiling', 'bolting', 'bombing', 'booking', 'boring',
    'borrowing', 'bouncing', 'bowing', 'boxing', 'braking', 'branching',
    'breaking', 'breathing', 'breeding', 'briefing', 'bringing', 'broadcasting',
    'bruising', 'brushing', 'bubbling', 'budgeting', 'building', 'bumping',
    'burning', 'bursting', 'burying', 'busting', 'buying', 'buzzing',
    'calculating', 'calling', 'camping', 'caring', 'carrying', 'carving',
    'casting', 'cataloging', 'catching', 'causing', 'challenging', 'changing',
    'charging', 'charting', 'chasing', 'cheating', 'checking', 'cheering',
    'chewing', 'choking', 'choosing', 'chopping', 'claiming', 'clapping',
    'clarifying', 'classifying', 'cleaning', 'clearing', 'clinging', 'clipping',
    'closing', 'clothing', 'coaching', 'coiling', 'collecting', 'coloring',
    'combing', 'coming', 'commanding', 'communicating', 'comparing',
    'competing', 'compiling', 'complaining', 'completing', 'composing',
    'computing', 'conceiving', 'concentrating', 'conceptualizing',
    'concerning', 'concluding', 'conducting', 'confessing', 'confronting',
    'confusing', 'connecting', 'conserving', 'considering', 'consisting',
    'consolidating', 'constructing', 'consulting', 'containing', 'continuing',
    'contracting', 'controlling', 'converting', 'coordinating', 'copying',
    'correcting', 'correlating', 'costing', 'coughing', 'counselling',
    'counting', 'covering', 'cracking', 'crashing', 'crawling', 'creating',
    'creeping', 'critiquing', 'crossing', 'crushing', 'crying', 'curing',
    'curling', 'curving', 'cutting', 'cycling', 'damaging', 'damming',
    'dancing', 'daring', 'dealing', 'decaying', 'deceiving', 'deciding',
    'decorating', 'defining', 'delaying', 'delegating', 'delighting',
    'delivering', 'demonstrating', 'depending', 'describing', 'deserting',
    'deserving', 'designing', 'destroying', 'detailing', 'detecting',
    'determining', 'developing', 'devising', 'diagnosing', 'digging',
    'directing', 'disagreeing', 'disappearing', 'disapproving', 'disarming',
    'discovering', 'disliking', 'dispensing', 'displaying', 'disproving',
    'dissecting', 'distributing', 'diverting', 'dividing', 'diving', 'doing',
    'doubling', 'doubting', 'drafting', 'dragging', 'draining', 'dramatizing',
    'drawing', 'dreaming', 'dressing', 'drinking', 'dripping', 'driving',
    'dropping', 'drowning', 'drumming', 'drying', 'dusting', 'dwelling',
    'earning', 'eating', 'editeing', 'educating', 'eliminating',
    'embarrassing', 'employing', 'emptying', 'enacting', 'encouraging',
    'ending', 'enduring', 'enforcing', 'engineering', 'enhancing', 'enjoying',
    'enlisting', 'ensuring', 'entering', 'entertaining', 'escaping',
    'establishing', 'estimating', 'evaluating', 'examining', 'exceeding',
    'exciting', 'excusing', 'executing', 'exercising', 'exhibiting',
    'existing', 'expanding', 'expecting', 'expediting', 'experimenting',
    'explaining', 'exploding', 'expressing', 'extending', 'extracting',
    'facilitating', 'facing', 'fading', 'failing', 'fancying', 'fastening',
    'faxing', 'fearing', 'feeding', 'feeling', 'fencing', 'fetching',
    'fighting', 'filing', 'filling', 'filming', 'finalizing', 'financing',
    'finding', 'firing', 'fitting', 'fixing', 'flapping', 'flashing', 'fleeing',
    'flinging', 'floating', 'flooding', 'flowering', 'flowing', 'flying',
    'folding', 'following', 'fooling', 'forbidding', 'forcing', 'forecasting',
    'foregoing', 'foreseeing', 'foretelling', 'forgetting', 'forgiving',
    'forming', 'formulating', 'forsaking', 'framing', 'freezing',
    'frightening', 'frying', 'gathering', 'gazing', 'generating', 'getting',
    'giving', 'glowing', 'gluing', 'going', 'governing', 'grabbing',
    'graduating', 'grating', 'greasing', 'greeting', 'grinding', 'grinning',
    'gripping', 'groaning', 'growing', 'guaranteeing', 'guarding', 'guessing',
    'guiding', 'hammering', 'handing', 'handling', 'hanging', 'happening',
    'harassing', 'harming', 'hating', 'haunting', 'heading', 'healing',
    'heaping', 'hearing', 'heating', 'helping', 'hiding', 'hitting', 'holding',
    'hoping', 'hopping', 'hovering', 'hugging', 'humming', 'hunting',
    'hurrying', 'hurting', 'hypothesizing', 'identifying', 'ignoring',
    'illustrating', 'imagining', 'implementing', 'impressing', 'improving',
    'improvising', 'including', 'increasing', 'inducing', 'influencing',
    'informing', 'initiating', 'injecting', 'injuring', 'innovating',
    'inputting', 'inspecting', 'inspiring', 'installing', 'instituting',
    'instructing', 'insuring', 'integrating', 'intending', 'intensifying',
    'interesting', 'interfering', 'interlaying', 'interpreting',
    'interrupting', 'interviewing', 'introducing', 'inventing', 'inventorying',
    'investigating', 'inviting', 'irritating', 'itching', 'jailing', 'jamming',
    'jogging', 'joining', 'joking', 'judging', 'juggling', 'jumping',
    'justifying', 'keeping', 'kicking', 'killing', 'kissing', 'kneeling',
    'knitting', 'knocking', 'knotting', 'knowing', 'labelling', 'landing',
    'lasting', 'laughing', 'launching', 'laying', 'leading', 'leaning',
    'leaping', 'learning', 'leaving', 'lecturing', 'ledding', 'lending',
    'letting', 'levelling', 'licensing', 'licking', 'lifting', 'lightening',
    'lighting', 'liking', 'listening', 'listing', 'living', 'loading',
    'locating', 'locking', 'logging', 'longing', 'looking', 'losing', 'loving',
    'lying', 'maintaining', 'making', 'managing', 'manipulating', 'manning',
    'manufacturing', 'mapping', 'marching', 'marketing', 'marking', 'marrying',
    'matching', 'mating', 'mattering', 'meaning', 'measuring', 'meddling',
    'mediating', 'meeting', 'melting', 'memorizing', 'mending', 'mentoring',
    'milking', 'mining', 'misleading', 'missing', 'misspelling', 'mistaking',
    'mixing', 'moaning', 'modelling', 'modifying', 'monitoring', 'mooring',
    'motivating', 'mourning', 'moving', 'mowing', 'muddling', 'mugging',
    'multiplying', 'murdering', 'nailing', 'naming', 'navigating', 'needing',
    'negotiating', 'nesting', 'nodding', 'nominating', 'normalizing',
    'noticing', 'noting', 'numbering', 'obeying', 'objecting', 'observing',
    'obtaining', 'occuring', 'offending', 'offering', 'officiating', 'opening',
    'operating', 'ordering', 'organizing', 'orienting', 'originating',
    'overcoming', 'overdoing', 'overdrawing', 'overflowing', 'overhearing',
    'overtaking', 'overthrowing', 'owning', 'packing', 'paddling', 'painting',
    'parking', 'participating', 'parting', 'passing', 'pasting', 'patting',
    'pausing', 'paying', 'pecking', 'pedalling', 'peeling', 'peeping',
    'perceiving', 'perfecting', 'performing', 'permitting', 'persuading',
    'phoning', 'photographing', 'picking', 'piloting', 'pinching', 'pining',
    'pinpointing', 'pioneering', 'placing', 'planning', 'planting', 'playing',
    'pleading', 'pleasing', 'plugging', 'pointing', 'poking', 'polishing',
    'popping', 'possessing', 'posting', 'pouring', 'practicing', 'praising',
    'praying', 'preaching', 'preceding', 'predicting', 'preferring',
    'preparing', 'prescribing', 'presenting', 'preserving', 'presetting',
    'presiding', 'pressing', 'pretending', 'preventing', 'pricking',
    'printing', 'processing', 'procuring', 'producing', 'professing',
    'programming', 'progressing', 'projecting', 'promising', 'promoting',
    'proofreading', 'proposing', 'protecting', 'providing', 'proving',
    'publicizing', 'pulling', 'pumping', 'punching', 'puncturing', 'punishing',
    'purchasing', 'pushing', 'putting', 'qualifying', 'questioning',
    'queueing', 'quitting', 'racing', 'radiating', 'raining', 'raising',
    'ranking', 'rating', 'reaching', 'reading', 'realigning', 'realizing',
    'reasoning', 'receiving', 'recognizing', 'recommending', 'reconciling',
    'recording', 'recruiting', 'reducing', 'referring', 'reflecting',
    'refusing', 'regretting', 'regulating', 'rehabilitating', 'reigning',
    'reinforcing', 'rejecting', 'rejoicing', 'relating', 'relaxing',
    'releasing', 'relying', 'remaining', 'remembering', 'reminding',
    'removing', 'rendering', 'reorganizing', 'repairing', 'repeating',
    'replacing', 'replying', 'reporting', 'representing', 'reproducing',
    'requesting', 'rescuing', 'researching', 'resolving', 'responding',
    'restoring', 'retiring', 'retrieving', 'returning', 'reviewing',
    'revising', 'rhyming', 'riding', 'ringing', 'rinsing', 'rising', 'risking',
    'robbing', 'rocking', 'rolling', 'rubbing', 'ruining', 'ruling', 'running',
    'rushing', 'sacking', 'sailing', 'satisfying', 'saving', 'sawing',
    'saying', 'scaring', 'scattering', 'scheduling', 'scolding', 'scorching',
    'scraping', 'scratching', 'screaming', 'screwing', 'scribbling',
    'scrubbing', 'sealing', 'searching', 'securing', 'seeing', 'seeking',
    'selecting', 'selling', 'sending', 'sensing', 'separating', 'servicing',
    'serving', 'setting', 'settling', 'sewing', 'shading', 'shaking',
    'shaping', 'sharing', 'shaving', 'shearing', 'shedding', 'sheltering',
    'shining', 'shivering', 'shocking', 'shoing', 'shooting', 'shopping',
    'showing', 'shrinking', 'shrugging', 'shutting', 'sighing', 'signalling',
    'signing', 'simplifying', 'singing', 'sinking', 'sinning', 'sipping',
    'sitting', 'sketching', 'skiing', 'skipping', 'slapping', 'slaying',
    'sleeping', 'sliding', 'slinging', 'slinking', 'slipping', 'slitting',
    'slowing', 'smashing', 'smelling', 'smiling', 'smoking', 'snatching',
    'sneaking', 'sneezing', 'sniffing', 'snoring', 'soaking', 'solving',
    'soothing', 'soothsaying', 'sorting', 'sounding', 'sowing', 'sparing',
    'sparking', 'sparkling', 'speaking', 'specifying', 'speeding', 'spelling',
    'spending', 'spilling', 'spinning', 'spitting', 'splitting', 'spoiling',
    'spotting', 'spraying', 'spreading', 'springing', 'sprouting', 'squashing',
    'squeezing', 'staining', 'stamping', 'standing', 'staring', 'starting',
    'staying', 'stealing', 'steering', 'stepping', 'sticking', 'stimulating',
    'stinging', 'stinking', 'stirring', 'stitching', 'stopping', 'storing',
    'strapping', 'streamlining', 'strengthening', 'stretching', 'striding',
    'striking', 'stringing', 'stripping', 'striving', 'stroking', 'structuring',
    'studying', 'stuffing', 'subletting', 'subtracting', 'succeeding',
    'sucking', 'suffering', 'suggesting', 'suiting', 'summarizing',
    'supervising', 'supplying', 'supporting', 'supposing', 'surprising',
    'surrounding', 'suspecting', 'suspending', 'swearing', 'sweating',
    'sweeping', 'swelling', 'swimming', 'swinging', 'switching', 'symbolizing',
    'synthesizing', 'systemizing', 'tabulating', 'taking', 'talking', 'taming',
    'tapping', 'targetting', 'tasting', 'teaching', 'tearing', 'teasing',
    'telephoning', 'telling', 'tempting', 'terrifying', 'testing', 'thanking',
    'thawing', 'thinking', 'thriving', 'throwing', 'thrusting', 'ticking',
    'tickling', 'tipping', 'tiring', 'touching', 'touring', 'towing',
    'tracing', 'trading', 'training', 'transcribing', 'transferring',
    'transforming', 'translating', 'transporting', 'trapping', 'travelling',
    'treading', 'treating', 'trembling', 'tricking', 'tripping', 'trotting',
    'troubleshooting', 'troubling', 'trusting', 'trying', 'tugging',
    'tumbling', 'turning', 'tutoring', 'twisting', 'typing', 'understanding',
    'undertaking', 'undressing', 'unfastening', 'unifying', 'uniting',
    'unlocking', 'unpacking', 'untidying', 'updating', 'upgrading',
    'upholding', 'upsetting', 'utilizing', 'vanishing', 'verbalizing',
    'verifying', 'vexing', 'visiting', 'wailing', 'waiting', 'waking',
    'walking', 'wandering', 'wanting', 'warming', 'warning', 'washing',
    'wasting', 'watching', 'watering', 'waving', 'wearing', 'weaving',
    'wedding', 'weeping', 'weighing', 'welcoming', 'wending', 'wetting',
    'whining', 'whipping', 'whirling', 'whispering', 'whistling', 'winding',
    'winking', 'winning', 'wiping', 'wishing', 'withdrawing', 'withholding',
    'withstanding', 'wobbling', 'wondering', 'working', 'worrying', 'wraping',
    'wrecking', 'wrestling', 'wriggling', 'wringing', 'writing', 'xraying',
    'yawning', 'yelling', 'zipping', 'zooming']

ANIMALS = [
    'aardvark', 'akbash', 'akita', 'alligator', 'alpaca', 'antelope', 'ass',
    'babbler', 'baboon', 'badger', 'balinese', 'barnacle', 'bat', 'bear',
    'beaver', 'bison', 'bluebird', 'boa', 'boar', 'bonobo', 'brontosaurus',
    'buffalo', 'bulbul', 'bulldog', 'bushpig', 'butterfly', 'buzzard',
    'caiman', 'caracal', 'cheetah', 'chinook', 'chipmunk', 'cobra', 'cockatoo',
    'cod', 'cormorant', 'cougar', 'cow', 'crab', 'crane', 'crow', 'curlew',
    'desman', 'dingo', 'dinosaur', 'diplodocus', 'discus', 'dodo', 'dog',
    'dolphin', 'dormouse', 'dove', 'dragon', 'drever', 'dromedar', 'dugong',
    'dunker', 'eagle', 'earwig', 'elephant', 'elk', 'emu', 'fantail',
    'figbird', 'flamingo', 'fossa', 'fox', 'frog', 'gar', 'gazelle', 'gecko',
    'gerbil', 'gharial', 'gibbon', 'giraffe', 'gnatcatcher', 'gnu', 'goat',
    'goose', 'gopher', 'grasshopper', 'grebe', 'grizzly', 'guinea',
    'hammerhead', 'hammerkop', 'hamster', 'hare', 'harrier', 'hawk',
    'hedgehog', 'heron', 'herring', 'hippo', 'hornbill', 'horse',
    'hummingbird', 'hyena', 'hyrax', 'ibex', 'ibis', 'iguana', 'impala',
    'indri', 'jackal', 'kangaroo', 'kite', 'kiwi', 'koala', 'komodo', 'kraken',
    'kudu', 'ladybird', 'lark', 'lemming', 'lemur', 'leopard', 'lion',
    'lizard', 'lobster', 'lynx', 'magpie', 'mallard', 'maltese', 'manatee',
    'mara', 'marmot', 'marten', 'mayfly', 'meerkat', 'melba', 'mole',
    'mongoose', 'monkey', 'monkeydock', 'moose', 'mosqito', 'mudskipper',
    'narwhal', 'nightingale', 'nilgai', 'numbat', 'ocelot', 'okapi',
    'orangutan', 'orca', 'oribi', 'oriole', 'osprey', 'ostrich', 'otter',
    'pollock', 'owl', 'ox', 'oyster', 'panda', 'panther', 'parakeet',
    'parrot', 'peacock', 'pelican', 'penguin', 'pheasant', 'piculet',
    'pike', 'piranha', 'platypus', 'plover', 'pointer', 'poodle', 'porcupine',
    'possum', 'puffin', 'pug', 'puma', 'python', 'quail', 'quetzal', 'quokka',
    'quoll', 'rabbit', 'racoon', 'rat', 'rattlesnake', 'reindeer', 'rhino',
    'ringtail', 'roadrunner', 'robin', 'salmon', 'sambar', 'scallop',
    'seagull', 'seal', 'sealion', 'serval', 'shark', 'sheep', 'shelduck',
    'shoebill', 'skunk', 'sloth', 'snake', 'snipe', 'sparrow', 'spider',
    'spoonbill', 'squirrel', 'starfish', 'starling', 'stilt', 'stork',
    'sunbird', 'suricate', 'swan', 'talarasaurus', 'tapir', 'tarantula',
    'termite', 'tern', 'tiger', 'tit', 'torosaurus', 'tortoisen', 'toucan',
    'trasher', 'turkey', 'turtle', 'tyrannosaurus', 'urchin', 'urial',
    'velociraptor', 'vicuna', 'viper', 'vole', 'vulture', 'wallaby',
    'wallaroo', 'walrus', 'warbler', 'warthog', 'wasp', 'waxbill', 'weasel',
    'whale', 'wolf', 'wolwerine', 'wombat', 'woodchuck', 'woodpecker', 'worm',
    'woylie', 'wren', 'yak', 'zebra', 'zorilla', 'zorro']

def to_human_hash(hashstr):
    """Generate human-readable string from hash. It will use the first 28 bits
    of the hash to make a human-readable string on the format
    color-adverb-verb-animal."""

    number = int(hashstr[:7], 16)

    adverb_index = ((0b1111111111 << 18) & number) >> 18
    verb_index = ((0b1111111111 << 8) & number) >> 8
    animal_index = 0b11111111 & number

    return '%s-%s-%s' % (ADVERBS[adverb_index],
                         VERBS[verb_index],
                         ANIMALS[animal_index])

def from_human_hash(humanstr):
    """Return 28-bit hexadecimal string converted from human readable string."""
    (adverb, verb, animal) = humanstr.split('-')
    adverb_index = ADVERBS.index(adverb)
    verb_index = VERBS.index(verb)
    animal_index = ANIMALS.index(animal)

    number = (adverb_index << 18) + (verb_index << 8) + (animal_index)
    return hex(number)[2:]

def make_random_hash():
    """Testing function; make 28 bit random hash string"""
    import random
    ret = ''
    while len(ret) < 7:
        ret = ret + str(hex(int(random.random()*16)))[2:]
    return ret

def do_test():
    """Test functions in module. Run through a series of hashes and test"""

    print 'id 2.5:', to_human_hash('30add10')
    count = 0
    while count < 35:
        hashstr = make_random_hash()
        human = to_human_hash(hashstr)
        hashback = from_human_hash(human)
        print '%s %s: %s' % (hashstr, hashback, human)
        count = count + 1
if __name__ == "__main__":
    do_test()
